services:
  cache_redis:
    image: "redis:alpine"
    container_name: "redis_evaldoc"
    ports:
      - "127.0.0.1:6379:6379" 
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - "redis_data:/data"
volumes:
  redis_data:

  